config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]

  resources :teams, only: [:index, :new, :create] do
    resources :projects, only: [:index, :new, :create]
    resources :events, only: [:index]
    resource :settings, only: [:show, :update]
  end

  resources :projects, shallow: true do
    resources :todos, only: [:index, :new, :create, :update, :show, :destroy] do
      member do
        #关闭Todo
        patch :close
      end
    end
  end

  resources :todos, shallow: true do
    resources :comments, only: [:create, :index]
  end

  resources :sessions, only: [:create, :destroy, :new]

  root to: 'teams#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :team
  has_many :todos
  has_many :users, through: :accesses
  has_many :accesses
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login

  def index
    @team = Team.find(params[:team_id])
    render :index
  end

  def new
    @team = Team.find(params[:team_id])
    @project = Project.new
    render :new
  end

  def create
    @team = Team.find(params[:team_id])
    @project, res = current_user.create_project(params[:name], @team)
    if res
      redirect_to team_projects_path(@team)
    else
      render :new
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.slim
h1 =@team.name
= link_to('返回团队列表', teams_path)
span |
= link_to('查看项目动态', team_events_path(team_id: @team.id))
span |
= link_to('设置可访问项目', team_settings_path(team_id: @team.id))
h3 项目列表
- if @team.projects.empty?
  p 当前还没有任何项目

ul
  - current_user.projects.each do |project|
    li =link_to(project.name, project_todos_path(project_id: project.id))
= link_to '创建新项目', new_team_project_path(@team)

app/views/projects/new.html.slim
= form_for([@team, @project])
  = label_tag(:name, '项目名称')
  = text_field_tag(:name)
  = submit_tag('创建项目')