config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]

  resources :teams, only: [:index, :new, :create] do
    resources :projects, only: [:index, :new, :create]
    resources :events, only: [:index]
    resource :settings, only: [:show, :update]
  end

  resources :projects, shallow: true do
    resources :todos, only: [:index, :new, :create, :update, :show, :destroy] do
      member do
        #关闭Todo
        patch :close
      end
    end
  end

  resources :todos, shallow: true do
    resources :comments, only: [:create, :index]
  end

  resources :sessions, only: [:create, :destroy, :new]

  root to: 'teams#index'
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  belongs_to :executor, class_name: 'User', foreign_key: 'executor_id'

  belongs_to :project
  has_many :comments

  after_create :send_create_event
  before_update :send_change_event
  after_destroy :send_destroy_event

  #进行中的任务
  scope :on_processing, ->{
    where(state: 'opened')
  }

  def update_attributes_by_user!(actor, params)
    @actor = actor
    self.update_attributes!(params)
  end

  def destroy_by(actor)
    @actor = actor
    self.destroy
  end

  #分配任务执行者
  def assign_executor!(executor)
    self.executor = executor
    save!
  end

  #关闭任务
  def close!(closer)
    unless self.state == 'opened'
      return
    end

    self.state = 'closed'
    save!
    send_close_todo_event(closer)
  end

  #重新打开任务
  def reopen!()
    self.state = 'opened'
    save!
  end

  private
  def send_create_event
    options = {action: 'todo_create', todo: self}
    if self.executor
      options[:meta_data] = {executor_name: executor.username}
    end
    Event.build(options)
  end

  def send_change_event
    changed = false
    #修改了任务的截止时间
    if self.deadline_changed?
      deadline_change = self.changes['deadline']
      from = deadline_change[0]
      to = deadline_change[1]
      action = 'change_deadline'
      changed = true
    end

    if self.executor_id_changed?
      executor_change = self.changes['executor_id']
      from_id = executor_change[0]
      to_id = executor_change[1]

      if from_id
        from = User.find(from_id).username
      else
        from = nil
      end

      to = User.find(to_id).username
      changed = true
      action = 'change_executor'
    end

    if changed
      options = {action: action, todo: self, from: from, to: to}
      if @actor
        options[:actor_name] = @actor.username
        options[:actor_id] = @actor.id
      end
      Event.build(options)
    end
  end

  def send_destroy_event
    options = {action: 'destroy_todo', todo: self}
    if @actor
      options[:actor_name] = @actor.username
      options[:actor_id] = @actor.id
    end
    Event.build(options)
  end

  def send_close_todo_event(closer)
    options = {action: 'close_todo', todo: self, actor_name: closer.username, actor_id: closer.id}
    Event.build(options)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :require_login

  def new
    @todo = Todo.new
    @project = Project.where(id: params[:project_id]).includes(:users).first
  end

  def index
    @project = Project.find(params[:project_id])
    @todos = @project.todos.on_processing
  end

  def create
    @project = Project.find(params[:project_id])

    @todo = Todo.new(todo_params)
    @todo.creator = current_user
    @todo.project = @project
    if @todo.save
      redirect_to project_todos_path(project_id: @project.id)
    else
      render 'new'
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def update
    todo = Todo.find(params[:id])
    todo.update_attributes_by_user!(current_user, todo_params)
    redirect_to todo_path(todo)
  end

  def close
    todo = Todo.find(params[:id])
    todo.close!(current_user)
    redirect_to project_todos_path(project_id: todo.project.id)
  end

  def destroy
    todo = Todo.find(params[:id])
    project_id = todo.project_id
    todo.destroy_by(current_user)
    redirect_to project_todos_path(project_id: todo.project.id)
  end

  private
  def todo_params
    params.require(:todo).permit(:executor_id, :content, :deadline)
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/index.html.slim
h2 当前项目: #{@project.name}
= link_to('返回项目列表', team_projects_path(team_id: @project.team))
h3 Todo列表
=link_to('新建Todo', new_project_todo_path(project_id: @project.id))

- if @todos.empty?
  p 当前还没有Todo
- else
  table
    tr
      th
        | 任务内容
      th
        | 完成时间
      th
        | 指派给
      th
        | 操作
    - @todos.each do |todo|
      tr
        td #{todo.content}
        td #{todo.deadline || '未指定'}
        td
          - if todo.executor
            | #{todo.executor.username}
          - else
            | 未指派
        td
          = link_to('修改', todo_path(todo))
          |
          = link_to('评论', todo_comments_path(todo_id: todo))
          = button_to "完成任务", {action: :close, id: todo.id}, {confirm: '确定要完成任务吗？', method: :patch}
          = button_to "删除任务", todo, :method => :delete

app/views/todos/new.html.slim
- if @todo.errors.any?
  ul
    - @todo.errors.full_messages.each do |msg|
      li = msg
= form_for([@project, @todo]) do |f|
  p
    = f.label(:content, 'Todo内容')
    = f.text_area(:content)
  p
    = f.label(:deadline, '项目完成时间')
    = f.datetime_local_field(:deadline)
  p
    = f.label(:executor_id, '执行人')
    = f.select "executor_id", options_from_collection_for_select(@project.users, 'id', 'username', include_blank: true)

  = f.submit('创建Todo')

app/views/todos/show.html.slim
= form_for(@todo) do |f|
  p
    = f.label(:content, 'Todo内容')
    = f.text_area(:content)
  p
    = f.label(:deadline, '项目完成时间')
    = f.datetime_local_field(:deadline)
  p
    = f.label(:executor_id, '执行人')
    = f.select "executor_id", options_from_collection_for_select(@todo.project.users, 'id', 'username', @todo.executor_id)

  = f.submit('修改Todo')